#!/bin/bash
# agent-core Bootstrap — SessionStart-Hook.
#
# WOZU. agent-cores eigener Auto-Sync (`agent-core-sync.sh`) haengt in
# `~/.claude/settings.json`, also im GLOBAL-Scope. Der reist nicht mit dem Repo:
# in einer Web-Session (Claude Code on the web) ist der Container frisch, `~/.claude`
# leer, und damit ist der Hook, der syncen soll, selbst nicht installiert. Henne-Ei.
# Dieses Script ist die andere Haelfte: es ist COMMITTET, faehrt also ueberall mit,
# wo das Repo hinkommt.
#
# WAS ES ZUSICHERT — eine einzige Invariante, und zwar die, auf die es ankommt:
# die IMMER geladenen agent-core-Regeln (`00-core`, `20-workflow`,
# `25-orchestration`, `30-quality`, `40-language`, ...) sind in diesem Checkout
# vorhanden. Erfuellt ist sie auf genau zwei Wegen:
#   (a) `CLAUDE.md` gehoert agent-core (GENERATED-Kopfzeile) -> der Kern steht darin, oder
#   (b) `.claude/rules/00-core.md` existiert -> der Kern liegt als Datei vor (ADR-0049).
# Beides zaehlt gleich viel; eine Datei in `.claude/rules/` OHNE Frontmatter laedt
# unbedingt, mit CLAUDE.md-Rang.
#
# WAS ES TUT, in dieser Reihenfolge:
#   1. Invariante + Version stimmen  -> STILL beenden. Der Normalfall macht nichts
#      und erzeugt keinen Diff; ein Hook, der bei jedem Sitzungsstart den Arbeitsbaum
#      anfasst, wird zu Rauschen und dann ignoriert.
#   2. agent-core ausfuehrbar        -> `sync --scope project` und kurz berichten,
#      was sich geaendert hat.
#   3. agent-core nicht auffindbar UND Invariante verletzt -> LAUT melden. Das ist
#      der Fall, in dem eine Sitzung sonst ohne den Arbeitsvertrag laeuft und es
#      NICHT merkt -- genau die stille Variante, die es zu vermeiden gilt.
#   4. agent-core nicht auffindbar, Invariante erfuellt -> STILL. Der committete
#      Stand traegt; er ist vielleicht aelter, aber er ist da.
#
# FAIL-OPEN gegenueber der Sitzung: dieses Script beendet IMMER mit 0. Ein kaputter
# Bootstrap darf keinen Sitzungsstart verhindern. Deshalb KEIN `set -e`.
#
# Diese Datei ist in allen sechs Gate-Repos byte-identisch (wie
# `pre-commit-gates.sh`). Wer sie aendert, aendert alle sechs.

set -u

# Die SessionStart-Nutzlast kommt auf stdin. Sie wird nicht ausgewertet, muss aber
# gelesen werden, sonst kann der Schreiber auf der anderen Seite blockieren.
cat >/dev/null 2>&1

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-}"
if [ -z "$PROJECT_DIR" ]; then
  PROJECT_DIR="$(cd "$(dirname "$0")/../.." 2>/dev/null && pwd)" || exit 0
fi
[ -d "$PROJECT_DIR" ] || exit 0

MANIFEST="$PROJECT_DIR/.claude/.agent-core-manifest.json"
CORE_RULE="$PROJECT_DIR/.claude/rules/00-core.md"
CLAUDE_MD="$PROJECT_DIR/CLAUDE.md"

# ── Meldekanal ────────────────────────────────────────────────────────────────
# Eine SessionStart-Meldung geht als `additionalContext` in den Sitzungskontext.
# JSON wird mit node gebaut, nie von Hand zusammengeklebt: der Text enthaelt
# Pfade, Anfuehrungszeichen und Zeilenumbrueche, und ein handgebautes JSON, das
# daran zerbricht, verschluckt die Meldung genau dann, wenn sie am noetigsten ist.
emit() {
  command -v node >/dev/null 2>&1 || { printf '%s\n' "$1" >&2; return 0; }
  MSG="$1" node -e '
    const msg = process.env.MSG || "";
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: msg },
    }));
  ' 2>/dev/null || printf '%s\n' "$1" >&2
}

json_field() {
  # $1 = Datei, $2 = Feldname. Leer, wenn Datei/Feld fehlt oder das JSON kaputt ist.
  [ -f "$1" ] || return 0
  command -v node >/dev/null 2>&1 || return 0
  F="$1" K="$2" node -e '
    const fs = require("fs");
    try {
      const j = JSON.parse(fs.readFileSync(process.env.F, "utf8"));
      const v = j[process.env.K];
      if (typeof v === "string") process.stdout.write(v);
    } catch {}
  ' 2>/dev/null
}

# ── Invariante ────────────────────────────────────────────────────────────────
core_present() {
  [ -f "$CORE_RULE" ] && return 0
  [ -f "$CLAUDE_MD" ] && head -c 200 "$CLAUDE_MD" 2>/dev/null | grep -q "GENERATED by @gmolike/agent-core" && return 0
  return 1
}

# ── agent-core finden ─────────────────────────────────────────────────────────
# Vier Stufen, in Reihenfolge abnehmender Verlaesslichkeit. Ergebnis ist MODE (+
# CLI_PATH fuer die node-Stufe); aufgerufen wird ueber `run_agent_core`, NICHT ueber
# einen in einer Variablen zusammengebauten Befehl: ein Pfad mit Leerzeichen
# (`C:/Program Files/...`, ein Benutzername mit Leerzeichen) wuerde dabei still in
# zwei Argumente zerfallen und der Bootstrap scheiterte an etwas, das wie ein
# fehlendes agent-core aussieht.
MODE=""
CLI_PATH=""
find_runner() {
  if command -v agent-core >/dev/null 2>&1; then
    MODE="bin"
    return 0
  fi
  if command -v node >/dev/null 2>&1; then
    for base in "${AGENT_CORE_HOME:-}" "$PROJECT_DIR/../agent-core" "$HOME/agent-core"; do
      [ -n "$base" ] || continue
      if [ -f "$base/dist/cli.js" ]; then
        MODE="node"
        CLI_PATH="$base/dist/cli.js"
        return 0
      fi
    done
  fi
  # npx zieht aus einer PRIVATEN Registry (GitHub Packages) und braucht einen Token
  # mit `read:packages`. Ohne den haengt oder scheitert der Aufruf -- im Sitzungsstart
  # beides teuer. Darum nur auf ausdrueckliche Freigabe.
  if [ "${AGENT_CORE_ALLOW_NPX:-0}" = "1" ] && command -v npx >/dev/null 2>&1; then
    MODE="npx"
    return 0
  fi
  return 1
}

run_agent_core() {
  case "$MODE" in
    bin) agent-core "$@" ;;
    node) node "$CLI_PATH" "$@" ;;
    npx) npx --yes @gmolike/agent-core "$@" ;;
    *) return 127 ;;
  esac
}

VENDORED="$(json_field "$MANIFEST" version)"

if ! find_runner; then
  if core_present; then
    exit 0 # Stufe 4: der committete Stand traegt.
  fi
  # Stufe 3: hier laeuft die Sitzung sonst ohne Arbeitsvertrag und merkt es nicht.
  emit "agent-core BOOTSTRAP: Die immer geladenen agent-core-Regeln fehlen in diesem Checkout ($PROJECT_DIR) — weder eine agent-core-generierte CLAUDE.md noch .claude/rules/00-core.md. Diese Sitzung laeuft OHNE 00-core / 20-workflow / 25-orchestration / 30-quality / 40-language. Ein ausfuehrbares agent-core wurde nicht gefunden (weder auf PATH noch unter \$AGENT_CORE_HOME, ../agent-core oder ~/agent-core). Abhilfe: agent-core danebenlegen und bauen (pnpm install && pnpm build), dann 'agent-core sync --scope project --dir $PROJECT_DIR'; oder AGENT_CORE_ALLOW_NPX=1 setzen, wenn ein Token mit read:packages vorliegt. Bis dahin: die Projektregeln unter .claude/rules/ gelten weiterhin, der agent-core-Kern nicht."
  exit 0
fi

AVAILABLE="$(run_agent_core --version 2>/dev/null | tr -d '\r\n')"

# Stufe 1: nichts zu tun. Gleiche Version UND Invariante erfuellt.
if [ -n "$AVAILABLE" ] && [ "$AVAILABLE" = "$VENDORED" ] && core_present; then
  exit 0
fi

# Stufe 2: syncen.
#
# VORHER: `.claude/settings.json` sichern und HINTERHER zurueckschreiben.
#
# Der Sync merged seine eigene settings.json hinein und ersetzt dabei `{{HOOKS_DIR}}`
# durch einen ABSOLUTEN Pfad der Maschine, auf der er lief
# (`targets/claude.ts`, `hooksDirPosix`). In einer Datei, die COMMITTET wird, ist das
# Gift: eine unter Windows erzeugte settings.json schickt jeden Hook nach
# `C:/Entwicklung/dnd/<repo>/.claude/hooks/...`, und in einem Linux-Container zeigt
# dieser Pfad ins Leere. Der Hook feuert dann nicht — ohne Fehler, ohne Meldung.
# Genau die stille Sorte Ausfall, gegen die dieser Bootstrap ueberhaupt gebaut ist.
#
# Deshalb gilt in diesem Workspace: `.claude/settings.json` ist HANDGEPFLEGT und
# nutzt `$CLAUDE_PROJECT_DIR`-relative Befehle (portabel, faehrt im Repo mit). Der
# Sync liefert Regeln, Skills, Agents und Hook-Skripte — die settings.json nicht.
#
# Gesichert wird der Datei-INHALT, nicht der git-Stand: ein `git checkout --` wuerde
# auch nicht committete Handaenderungen wegwerfen. So kommt exakt das zurueck, was
# vorher dastand, committet oder nicht.
SETTINGS="$PROJECT_DIR/.claude/settings.json"
SETTINGS_BAK=""
if [ -f "$SETTINGS" ]; then
  SETTINGS_BAK="$(mktemp 2>/dev/null || true)"
  [ -n "$SETTINGS_BAK" ] && cp "$SETTINGS" "$SETTINGS_BAK" 2>/dev/null
fi

# Die Sync-Ausgabe ist lang (>120 Zeilen) und gehoert nicht in den Sitzungskontext —
# gemeldet wird das Ergebnis, nicht das Protokoll.
SYNC_LOG="$(cd "$PROJECT_DIR" && run_agent_core sync --scope project --dir "$PROJECT_DIR" 2>&1)"
SYNC_RC=$?

if [ -n "$SETTINGS_BAK" ] && [ -f "$SETTINGS_BAK" ]; then
  cp "$SETTINGS_BAK" "$SETTINGS" 2>/dev/null
  rm -f "$SETTINGS_BAK" 2>/dev/null
fi

if [ "$SYNC_RC" -ne 0 ]; then
  emit "agent-core BOOTSTRAP: 'sync --scope project' ist mit Exit $SYNC_RC gescheitert (agent-core ${AVAILABLE:-unbekannt}, vendored ${VENDORED:-keins}). Diese Sitzung arbeitet mit dem committeten Stand. Letzte Zeilen: $(printf '%s' "$SYNC_LOG" | tail -5 | tr '\n' ' ')"
  exit 0
fi

NOW="$(json_field "$MANIFEST" version)"
if core_present; then
  if [ "$NOW" != "$VENDORED" ]; then
    emit "agent-core BOOTSTRAP: von ${VENDORED:-keinem Stand} auf $NOW gesynct. Der Arbeitsbaum enthaelt jetzt Aenderungen unter .claude/ — pruefen und committen (oder verwerfen), bevor andere Arbeit darauf aufsetzt."
  fi
  exit 0
fi

emit "agent-core BOOTSTRAP: 'sync' lief durch (agent-core ${AVAILABLE:-unbekannt}), aber der Kern ist danach WEDER in CLAUDE.md NOCH unter .claude/rules/00-core.md. Erwartbar nur mit agent-core < 2.0.1 (vor ADR-0049): dort hat eine handgeschriebene CLAUDE.md keinen Ersatzweg, und die Kernregeln erreichen keine Sitzung. Abhilfe: agent-core aktualisieren."
exit 0
